"""empty message

Revision ID: 8e77febba2fa
Revises: 986aec1ca3ba
Create Date: 2022-02-06 22:45:22.949965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e77febba2fa'
down_revision = '986aec1ca3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_URL_long', table_name='URL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_URL_long', 'URL', ['long'], unique=True)
    # ### end Alembic commands ###
